
download:
	docker pull yeasy/kafka:latest

start:
	docker-compose up
stop:
	docker-compose down

restart: stop start

zookeeper:
	docker exec -it zookeeper1 bash
kafka:
	docker exec -it kafka1 bash

cli:
	docker exec -it cli bash
